export const FilmsInfo = [
  {
    id: "1",
    name: "Avatar",
    cost: 70000,
    year: "2022",
    nation: "USA",
    img: "assets/images/avatar.jpg",
    info: "Avatar is the story of the 'reluctant' hero Jake Sully - a former Marine officer who is half-paralyzed. His twin brother was selected to participate in a gene transplant program with the alien Na'vi to create a new species that can breathe the air on the planet Pandora.",
  },
  {
    id: 2,
    name: "Mission Impossible : Fallout ",
    cost: 70000,
    year: "2018",
    nation: "United States",
    img: "assets/images/fallout.jpg",
    info: "Mission Impossible : Fallout is a 2018 American action spy film written and directed by Christopher McQuarrie. It is the sequel to Mission: Impossible – Rogue Nation (2015) and is the sixth installment in the Mission: Impossible film series. The film stars Tom Cruise, Ving Rhames, Simon Pegg, Rebecca Ferguson, Henry Cavill, Sean Harris, Michelle Monaghan, and Alec Baldwin. In Mission: Impossible – Fallout, Ethan Hunt (Cruise) and his Impossible Missions Force (IMF) team seek to prevent nuclear weapon technology from reaching the Apostles, a bioterrorist offshoot of the Syndicate.",
  },
  {
    id: 3,
    name: "Private of the Caribbean : At World's End",
    cost: 70000,
    year: "2007",
    nation: "United States",
    img: "assets/images/caribbean.jpg",
    info: "Pirates of the Caribbean: At World's End is a 2007 American epic fantasy swashbuckler film directed by Gore Verbinski, the third installment in the Pirates of the Caribbean film series and the sequel to Dead Man's Chest (2006). It follows Will Turner, Elizabeth Swann, Hector Barbossa, and the crew of the Black Pearl as they seek to rescue Captain Jack Sparrow from Davy Jones' Locker. They then prepare to fight the East India Trading Company, led by Cutler Beckett, who controls Davy Jones and plans to extinguish piracy forever.",
  },
  {
    id: 4,
    name: "The Dark Knight",
    cost: 70000,
    year: "2008",
    nation: "USA",
    img: "assets/images/batman.jpg",
    info: "The Dark Knight is a 2008 superhero film directed by Christopher Nolan from a screenplay he co-wrote with his brother Jonathan. Based on the DC Comics superhero Batman, it is the sequel to Batman Begins (2005) and the second installment in The Dark Knight Trilogy. The film follows the vigilante Batman, police lieutenant James Gordon, and district attorney Harvey Dent as they form an alliance to dismantle organized crime in Gotham City. Their efforts are derailed by the intervention of the Joker, an anarchistic mastermind who seeks to test how far Batman will go to save the city from complete chaos.",
  },
  {
    id: 5,
    name: "Smile",
    cost: 70000,
    year: "2022",
    nation: "USA",
    img: "assets/images/smile.jpg",
    info: "The film tells the story of female psychologist Rose Cotter, after witnessing a suicide of her patient, she herself is dragged into a mysterious loop that can affect the lives of her and those around her. around.",
  },
  {
    id: 6,
    name: "Spiderman : Far From Home",
    cost: 70000,
    year: "2019",
    nation: "USA",
    img: "assets/images/spiderman.jpg",
    info: "Spider-Man: Far From Home is a 2019 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios, and distributed by Sony Pictures Releasing. It is the sequel to Spider-Man: Homecoming (2017) and the 23rd film in the Marvel Cinematic Universe (MCU).",
  },
  {
    id: 7,
    name: "Thor : Love and Thunder",
    cost: 70000,
    year: "2022",
    nation: "USA",
    img: "assets/images/thor.jpg",
    info: "Thor: Love and Thunder is an American superhero film based on the Marvel Comics character of the same name. This is the sequel to Thor: Ragnarok Apocalypse, which will also be the 29th film in the Marvel Cinematic Universe. The film is produced by Marvel Studios and released by Walt Disney in 2022.",
  },
  {
    id: 8,
    name: "Avengers : Endgame",
    cost: 70000,
    year: "2019",
    nation: "North America",
    img: "assets/images/endgame.jpg",
    info: "Avengers: The End is an American superhero movie released in 2019, produced by Marvel Studios and exclusively distributed by Walt Disney Studios Motion Pictures in the North American market.  ",
  },
  {
    id: 9,
    name: "Joker (2019)",
    cost: 70000,
    year: "2019",
    nation: "USA",
    img: "assets/images/joker.jpg",
    info: "Joker is a 2019 American psychological thriller film directed and produced by Todd Phillips, with a screenplay written by him and screenwriter Scott Silver. The film is based on the original DC Comics comic book series, with the setting set in 1981 in Gotham City.",
  },
];
