export const FilmsInfo =[
    {id: 1, name: 'Avatar',
     year: '2022',
     nation:"USA",
      img:'https://i2.wp.com/kinomagasinet.no/wp-content/uploads/sites/3/2022/08/Avatar_Re-Release_1920x1080px_NO-1000x600.jpg',
      info:"Avatar is the story of the 'reluctant' hero Jake Sully - a former Marine officer who is half-paralyzed. His twin brother was selected to participate in a gene transplant program with the alien Na'vi to create a new species that can breathe the air on the planet Pandora."},
    {id: 2, name: 'There Are No Saints',
     year: '2022',
     nation:"USA",
      img:'https://i.rada.vn/data/image/2022/09/06/There-Are-No-Saints-1.jpg',
      info:"A man nicknamed 'the Jesuit', is imprisoned for a crime he didn't commit. When his wife is murdered and his son kidnapped and taken to Mexico, he devises an elaborate and dangerous plan to rescue his son and avenge the murder."},
    {id: 2, name: 'Semantic Error',
     year: '2022',
     nation:"Korea",
      img:'https://media.lottecinemavn.com/Media/MovieFile/MovieImg/202209/10954_105_100001.jpg',
      info:"Semantic Error is the movie version of Korea's most explosive Web-drama in early 2022. Choo Sang Woo - a dry, mechanical boy who lives in logical frameworks. Jang Jae Young - a talented, romantic guy who always ignores all rules to live life to the fullest with passion and youthful joy. Two people, two opposite directions in terms of life, but together they touch 'destiny'. Life that seemed to be full of 'errors' suddenly seemed to be full of flowers."},
    {id: 2, name: 'The Dark Knight',
     year: '2008',
     nation:"USA",
      img:'https://larepublica.pe/resizer/Qe11xUE9SX8euEF9b85d3AxqdC8=/1250x735/top/smart/cloudfront-us-east-1.images.arcpublishing.com/gruporepublica/TLBIGOIGTFGCBIU4TECGW7KOLA.jpg',
      info:"The Dark Knight is a 2008 superhero film directed by Christopher Nolan from a screenplay he co-wrote with his brother Jonathan. Based on the DC Comics superhero Batman, it is the sequel to Batman Begins (2005) and the second installment in The Dark Knight Trilogy. The film follows the vigilante Batman, police lieutenant James Gordon, and district attorney Harvey Dent as they form an alliance to dismantle organized crime in Gotham City. Their efforts are derailed by the intervention of the Joker, an anarchistic mastermind who seeks to test how far Batman will go to save the city from complete chaos."},
    {id: 2, name: 'Smile',
     year: '2022',
     nation:"USA",
      img:'https://scontent.fsgn5-6.fna.fbcdn.net/v/t39.30808-6/308187876_154057947312101_7078128650032329816_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=e3f864&_nc_ohc=A2hKj5pvuA0AX-YtLfj&_nc_ht=scontent.fsgn5-6.fna&oh=00_AT_KFn6kMInfuzRvqrd_NTYebZIQF_3Ab_lFxbSUQUZ-ng&oe=633660F4',
      info:"The film tells the story of female psychologist Rose Cotter, after witnessing a suicide of her patient, she herself is dragged into a mysterious loop that can affect the lives of her and those around her. around."},
    {id: 2, name: 'Spiderman : Far From Home',
     year: '2019',
     nation:"USA",
      img:'https://hosonhanvat.vn/wp-content/uploads/2019/05/Spider-man-1.jpg',
      info:"Spider-Man: Far From Home is a 2019 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios, and distributed by Sony Pictures Releasing. It is the sequel to Spider-Man: Homecoming (2017) and the 23rd film in the Marvel Cinematic Universe (MCU)."},
    {id: 2, name: 'Thor : Love and Thunder',
     year: '2022',
     nation:"USA",
      img:'https://o.rada.vn/data/image/2022/04/20/Thor-Love-and-Thunder-7.jpg',
      info:"Thor: Love and Thunder is an American superhero film based on the Marvel Comics character of the same name. This is the sequel to Thor: Ragnarok Apocalypse, which will also be the 29th film in the Marvel Cinematic Universe. The film is produced by Marvel Studios and released by Walt Disney in 2022."},
    {id: 2, name: 'Avengers : Endgame',
     year: '2019',
     nation:"North America",
      img:'https://photo-cms-plo.epicdn.me/w850/Uploaded/2022/wopsvun/2019_08_15/avengers-endgame_WAKU.jpg',
      info:"Avengers: The End is an American superhero movie released in 2019, produced by Marvel Studios and exclusively distributed by Walt Disney Studios Motion Pictures in the North American market.  "},
    {id: 2, name: 'Joker (2019)',
     year: '2019',
     nation:"USA",
      img:'https://khenphim.com/wp-content/uploads/2019/10/Joker-4-banner-512x277.jpg',
    info:"Joker is a 2019 American psychological thriller film directed and produced by Todd Phillips, with a screenplay written by him and screenwriter Scott Silver. The film is based on the original DC Comics comic book series, with the setting set in 1981 in Gotham City."}
  ];
